[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
marketplace = "7VEP39wxE8vD2biZw6fzBemgiE9oNyPHBrMMEMsvcAEj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/pradip/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
